name: jobbiteproject
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.1.1
  uuid: ^3.0.6 
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+1
  permission_handler: ^11.3.1
  bottom_navy_bar: ^6.0.0
  google_maps_flutter: ^2.5.3
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  customizable_counter: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
