// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqcxY2FHiInIT-0T0fC8PKsv3bGvoSluo',
    appId: '1:1027620664462:web:01262b856fb0d4babfc5df',
    messagingSenderId: '1027620664462',
    projectId: 'jobbite-5a8b5',
    authDomain: 'jobbite-5a8b5.firebaseapp.com',
    storageBucket: 'jobbite-5a8b5.appspot.com',
    measurementId: 'G-85V6GG964Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqh1Z25mUdP3e7Xc_GPLgpXjllKz7nF8k',
    appId: '1:1027620664462:android:668b874df7103280bfc5df',
    messagingSenderId: '1027620664462',
    projectId: 'jobbite-5a8b5',
    storageBucket: 'jobbite-5a8b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsa_iqC0aCQXHVBCQfR_4jU8Ga_5KQVAo',
    appId: '1:1027620664462:ios:01b2da774c285625bfc5df',
    messagingSenderId: '1027620664462',
    projectId: 'jobbite-5a8b5',
    storageBucket: 'jobbite-5a8b5.appspot.com',
    iosBundleId: 'com.example.jobbite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsa_iqC0aCQXHVBCQfR_4jU8Ga_5KQVAo',
    appId: '1:1027620664462:ios:01b2da774c285625bfc5df',
    messagingSenderId: '1027620664462',
    projectId: 'jobbite-5a8b5',
    storageBucket: 'jobbite-5a8b5.appspot.com',
    iosBundleId: 'com.example.jobbite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqcxY2FHiInIT-0T0fC8PKsv3bGvoSluo',
    appId: '1:1027620664462:web:607667bd0f479cc9bfc5df',
    messagingSenderId: '1027620664462',
    projectId: 'jobbite-5a8b5',
    authDomain: 'jobbite-5a8b5.firebaseapp.com',
    storageBucket: 'jobbite-5a8b5.appspot.com',
    measurementId: 'G-049P5CJXTV',
  );
}
